WIP: Implement github deployment logic
openSUSE/obs-deployment-tool pull request #15
Opened 2020-12-15 11:03 UTC by krauselukas

Co-authored-by: Eduardo Navarro <enavarro@suse.com>

2020-12-15 11:22 UTC, vpereira commented on lib/github_deployment.rb
> +      exit
Those `exit` are there just because we are runnig mina?

2020-12-15 12:01 UTC, eduardoj commented on lib/github_deployment.rb
> +      exit
We had that `if` clauses with `exit` calls inside mina tasks. The code has only been moved to a better place, but has not been adapted/refactored. Still work-in-progress.

2020-12-15 12:19 UTC, krauselukas commented on lib/github_deployment.rb
> +      exit
yes, I think that's why we used it. I guess we can just do a simple return if we not using mina

2020-12-15 15:18 UTC, krauselukas commented on lib/github_deployment.rb
> +      exit
we got rid of the exit, we use a regular return now

2020-12-16 11:16 UTC, saraycp commented on lib/github_deployment.rb
> +    return @all_github_deployments unless @all_github_deployments
This line confuses me a bit. Is really an `unless`what you need here?

2020-12-16 11:43 UTC, krauselukas commented on lib/github_deployment.rb
> +    return @all_github_deployments unless @all_github_deployments
yes, of course you are right @saraycp

2020-12-16 16:06 UTC, krauselukas commented on lib/github_deployment.rb
> +    return @all_github_deployments unless @all_github_deployments
@saraycp I was calling `empty?` on the `@all_github_deployments` thats why I used `unless`, somehow this got lost in the process

2020-12-16 16:13 UTC, danidoni commented on lib/github_deployment.rb
> +    end
I think you can do it shorter like this:
```suggestion
    return create_a_deployment_and_lock if deployment.nil? 
```

2020-12-16 16:19 UTC, danidoni commented on lib/github_deployment.rb
> +    perform_lock ||= false
This is kind of weird, I would initialize properly `perform_lock` a bit earlier

2020-12-16 16:34 UTC, krauselukas commented
@danidoni please have another look :)

2020-12-16 16:42 UTC, danidoni approved these changes

2020-12-16 16:46 UTC, vpereira requested changes

2020-12-16 16:46 UTC, vpereira commented on lib/github_deployment.rb
> +  def initialize(access_token, repository, ref)
In another methods we used keyword parameter,  as in https://github.com/openSUSE/obs-deployment-tool/blob/main/lib/obs_deploy/zypper.rb. It would be nice if we keep all other methods with the same structure.

2020-12-16 16:46 UTC, vpereira commented on lib/github_deployment.rb
> +    unless deployment_status.nil? || deployment_status.state == 'queued'
Looking the API, I think https://developer.github.com/v3/repos/deployments/#list-deployment-statuses return will be empty and not nil if nothing is found.  Maybe installing `ActiveSupport` and stick with the robust `blank?` and `present?` ?

Reference:  https://edgeguides.rubyonrails.org/active_support_core_extensions.html

2020-12-16 17:02 UTC, krauselukas commented on lib/github_deployment.rb
> +    unless deployment_status.nil? || deployment_status.state == 'queued'
I checked this, octokit returns `nil` but yes we can also pull in `active_support`

2020-12-16 17:53 UTC, krauselukas commented
@vpereira Applied your suggestions, the `active_support` was not strictly necessary, but it might also makes things easier in the future

2020-12-16 23:06 UTC, merged